### ISSUE TITLE
NameError: name 'cc' is not defined

### ISSUE THREAD

**Issue by thedam** [fredsanto/coverageMaster#4]
Hey, 
running command like: 
`python coverageMaster.py sample.cov sample.flagstat.txt -r total_ref_m_std -o out -b my.bed`

results in error:
```
Thu Sep 15 09:29:26 2022 - --------------------------------------------------------------------------------
CoverageMaster is warming up
Thu Sep 15 09:29:27 2022 - Query index created
Thu Sep 15 09:30:30 2022 - Reference index created
Thu Sep 15 09:30:30 2022 - Processing Gene: XIST - Region chrX:73040485-73072588
Traceback (most recent call last):
  File "/mnt/data/production/CNV/samDepths/refsout2/../../coverageMaster/coverageMaster.py", line 360, in <module>
    for n,c in enumerate(cc):
NameError: name 'cc' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/production/CNV/samDepths/refsout2/../../coverageMaster/coverageMaster.py", line 398, in <module>
    raise Exception("Error in __main__")
Exception: Error in __main__
```

indeed in coverageMaster.py `cc` is defined only in optional cases:
```
    try:
        signalBuffer = Manager().dict() 
        if options.control:
            cc = open(options.control).read().strip().split("\n")
        if options.single_control:
            cc = [options.single_control]
        for n,c in enumerate(cc):

```
`options.control` and `options.single_control` suppose to be optional
```
parser.add_option("-c",'--control',  dest="control", help = "<optional> txt file with a control file per line (.cov with .report.txt in same folder)")
parser.add_option("-s",'--single-control',  dest="single_control", help = "<optional> single control file (.cov with .report.txt in same folder)")

```

**Comment by thedam** [comment]
ok, it's just a matter of documentation...
